baseURL = "https://arnaduga.dev/"
languageCode = "zh-cn"
title = "Arnaduga's website"
theme = "github-style"

googleAnalytics = "UA-123456-789"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  goatCounter = "accountName"
  author = "MeiK"
  description = "In solitude, where we are least alone."
  github = "MeiK2333"
  facebook = "MeiK2333"
  twitter = "MeiK2333"
  linkedin = "MeiK2333"
  instagram = "MeiK2333"
  tumblr = "MeiK2333"
  email = "meik2333@gmail.com"
  url = "https://meik2333.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "China"
  userStatusEmoji = "😀"

  displayTagsList = true

  [[params.links]]
    title = "Link"
    href = "https://github.com/arnaduga"
  [[params.links]]
    title = "Link2"
    href = "https://arnaduga.dev"
    icon = "https://arnaduga.dev/images/avatar.png"


  [[params.options]]
    displayReadingTime = false
    displayLanguageSwitch = true
    displayNightCat = false

  [[params.translation]]
    language1suffix = ""
    language1code = "🇬🇧"
    language2suffix = ".fr"
    language2code = "🇫🇷"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
